### ISSUE TITLE
Always "...clicked at: (0, 0, 0)."

### ISSUE THREAD

**Issue by Saafke** [florianblume/6d-pat#99] opened 2020-06-22 16:15 UTC
Hello,

I successfully loaded my images and 3d model (i used .ply). But when I try to click on the 3D model (in the GUI) it always says I clicked at location (0,0,0), which is obviously not the case. What am I doing wrong?

I have set up my camera parametrics correctly as well.

**Comment by florianblume** [comment] 2020-07-01 10:58
Hey Saafke,

it's difficult to tell what the issue is. I suspect that you're not doing anything wrong but a bug in the code. Have you ever debugged C++ code? I suggest you step through the code and maybe save some intermediate artifacts of the code, e.g. the rendered object coordinate map of the pose editor. Unfortunately, I don't have time at the moment to look into you issue, sorry!

**Comment by florianblume** [comment] 2020-07-21 11:59
Will be solved with issue #49

**Comment by josh-yang92** [comment] 2020-10-21 17:01
Hi, thank you so much for your effort. I am facing the same problem but I am not experienced with C++ to debug the code myself. How is the progress on this issue?

**Comment by florianblume** [comment] 2020-10-23 12:19
Hey Josh,

thanks for your comment and interest in the program! Unfortunately, I'm doing a PhD at TU Berlin which is why I'm pretty busy and only slowly progressing. Right now I'm implementing the migration from pure OpenGL to Qt3D as the latter has all functions already implemented. This means that after the successful migration to Qt3D, textures will work, clicking should work with all datasets and so on. I migrated all widgets except for the pose viewer (the lower left widget). I'm not sure when I'll be able to finish but I'll try my best to make it quick!

Best,
Florian

**Comment by florianblume** [comment] 2020-11-29 10:24
Could  you verify that with the new release the issue is gone? I switched back to Qt3D and everything should work now :)

**Comment by josh-yang92** [comment] 2020-11-30 15:18
Hi, I cannot verify as now I cannot view my models. It seems like the model previews are loaded but when selected nothing happens (hopefully the image I am attaching to this comment will help you to see what I mean). 

Also, Is there a way to fit the image into that previewing window? My images are too big and it will be a bit difficult to drag each image into different positions :(

Thank you for your effort and reponse!

![Screenshot from 2020-11-30 17-12-06](https://user-images.githubusercontent.com/47159382/100627247-71c2bf80-332f-11eb-83f5-ac4054c572a8.jpg)

**Comment by florianblume** [comment] 2020-11-30 15:45
Could you send me a link to your models and images? I'll see what I can do. Actually there should be a zoom slider at the bottom of the pose viewer, I'm not sure why it's not there for you, it is for me!

**Comment by florianblume** [comment] 2020-11-30 15:47
Ah I see what's wrong, this is the old version of the program! Did you download the new release? It's on the main page to the right. Everything you need is bundled in there, so there shouldn't any conflicts with Qt or OpenCV versions. Just unpack everything (including the lib folder) to somewhere you like and launch the 6DPAT executable.

**Comment by florianblume** [comment] 2021-02-17 09:59
Have you tried out the new version in the meantime?

**Comment by florianblume** [comment] 2021-07-06 14:36
Closing since it doesn't seem to be active anymore.

**Closed** 2021-07-06 14:36 UTC
Labels: bug
