### ISSUE TITLE
Enabling 3D acceleration crashes program

### ISSUE THREAD

**Issue by JoaoGuimaraes98** [florianblume/6d-pat#147] opened 2021-10-26 18:20 UTC
I have installed Virtualbox 6 with ubuntu 20.04 VM. When I run the App image without 3D acceleration, the app works but I get very sluggish performance, always running at 1FPS. So I tried enabling 3D acceleration to improve performance but when I run the AppImage, the program shows the 3D PAT initial image but then it crashes.

The problem remains with and without Virtualbox guest additions installed.

**Comment by florianblume** [comment] 2021-11-03 07:21
I tried your data and I couldn't make the object visible either. It's really weird since Qt3D manages to show the program. Do you have the actual camera matrices? I used fake ones with image width, height and center as parameters. Maybe that would help.

**Comment by JoaoGuimaraes98** [comment] 2021-11-03 11:11
Yeah I have it, sending it attached
[intrinsics.txt](https://github.com/florianblume/6d-pat/files/7467116/intrinsics.txt)

**Comment by florianblume** [comment] 2021-11-04 10:29
I don't have time at the moment to look into this but will as soon as I can

**Comment by florianblume** [comment] 2021-11-26 10:05
Hey, I've got an update for you!

The problem is that the near plane must be set to lower values since your object is really small and thus close to the camera.

There it is:

![Screenshot from 2021-11-26 10-44-25](https://user-images.githubusercontent.com/2170192/143563215-84e30f83-c29c-411f-b5be-08a8bd4d0f73.png)

It was already possible to set near and far plane in the old code but I improved it. You can:

- Either set `nearPlane` and `farPlane` in the root of your `info.json` camera file, i.e. on the same level as the image entries. In this case, all images get this near plane and far plane (instead of the default values 50 and 2000), in case the you didn't...
- Set an individual `nearPlane` and `farPlane` on the image attributes itself.

I hope you get it to work now! Sorry that it took me so long, I was pretty busy.

**Comment by florianblume** [comment] 2021-11-26 10:06
But maybe consider rescaling your object to centimeters (right now it looks like it's in meters).

**Comment by florianblume** [comment] 2021-11-26 10:08
Be sure to checkout the latest release 2.4.3!

**Comment by florianblume** [comment] 2022-01-13 13:51
Closing this issue now, reopen if the problem still persists.

**Closed by florianblume** 2022-01-13 13:51 UTC
